language: php

php:
  - 5.4

before_script: 
  - composer install
  - rm -rf app/test
  - mkdir app/test
  - app/console --env=test doctrine:database:create
  - app/console --env=test doctrine:schema:create

script: phpunit -c app
