language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script: 
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - app/console --env=test doctrine:database:create

script: phpunit -c app
