language: php

php:
  - 5.4
  - 5.5

before_script: 
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install
  - app/console --env=test doctrine:database:create
  - app/console --env=test doctrine:schema:create
  - app/console --env=test doctrine:fixtures:load --append

script: phpunit -c app
