language: php

php:
  - 5.4

before_script: 
  - composer install
  - app/console --env=test --quiet doctrine:database:create
  - app/console --env=test --quiet doctrine:schema:create

script: phpunit -c app
