imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: doctrine_extensions.yml }

framework:
    #esi:             ~
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: %assets_version%
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
          google_analytics_account: %google.analytics.account%
          google_analytics_domain: %google.analytics.domain%
          scheme_and_host: %scheme_and_host%
          assets_version: %assets_version%
          bootstrap_version: 3.0.2
          jquery_version: 1.10.2
          barcamp_title: %barcamp_title%
          barcamp_description: %barcamp_description%
          barcamp_start_time: %barcamp_start_time%
          barcamp_end_time: %barcamp_end_time%
          barcamp_hashtag: %barcamp_hashtag%
          barcamp_location_longitude: %barcamp_location_longitude%
          barcamp_location_latitude: %barcamp_location_latitude%
          twitter_widget_id: %twitter_widget_id%

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        [ BCRMWebBundle ]
    java:           %java_bin%
    filters:
        cssrewrite:
          apply_to: "\.css$"
        sass:
          bin:      %sass_bin%
          apply_to: "\.scss$"
        #closure:
        #    jar: %kernel.root_dir%/Resources/java/compiler.jar
        yui_css:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar
        yui_js:
            jar: %kernel.root_dir%/Resources/java/yuicompressor-2.4.8.jar

# Doctrine Configuration
doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    port:      %mailer_port%
    spool:     { type: file, path: %kernel.root_dir%/spool }

# LiteCQRS Configuration
lite_cqrs:
    crud:     true
    orm:      true

bcrm_web:
    content_dir: %web.content_dir%

coderbyheart_mail_chimp:
  api_key: %mailchimp.api_key%
