security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_CONCIERGE:   ROLE_USER
        ROLE_ADMIN:       [ROLE_CONCIERGE, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    concierge:  { password: %password.concierge%, roles: [ 'ROLE_CONCIERGE' ] }

    encoders:
            Symfony\Component\Security\Core\User\User: plaintext

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        checkin:
            pattern:    ^/(checkin|concierge)
            http_basic:
                realm: "BarCamp RheinMain Checkin-Area"

    access_control:
        - { path: ^/(checkin|concierge), roles: ROLE_CONCIERGE }
