security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_CONCIERGE:   ROLE_USER
        ROLE_ADMIN:       [ROLE_CONCIERGE, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        checkin:
            pattern:    ^/checkin/
            http_basic:
                realm: "BarCamp RheinMain Checkin-Area"

    access_control:
        - { path: ^/checkin/, roles: ROLE_CONCIERGE }
