# Static pages
bcrmweb_index:
    path: /
    methods:  [GET]
    defaults:
        _controller: bcrm.web.controller.web:indexAction

bcrmweb_page:
    path: /p/{path}
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
    requirements:
        path: ".+"

bcrmweb_content:
    path: /c/{path}
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:contentAction
    requirements:
        path: ".+"

bcrmweb_newsletter_subscribe:
    path: /newsletter/subscribe
    methods: [POST]
    defaults:
        _controller: bcrm.web.controller.newsletter:subscribeAction

bcrmweb_newsletter_ok:
    path: /newsletter/ok
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
        path: Newsletter/Ok

bcrmweb_newsletter_already_subscribed:
    path: /newsletter/schon-drin
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
        path: Newsletter/SchonDrin

bcrm_newsletter_confirm:
    path: /newsletter/confirm/{id}/{key}
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.newsletter:confirmAction

bcrmweb_newsletter_confirmed:
    path: /newsletter/aktiviert
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
        path: Newsletter/Aktiviert
        
bcrmweb_event_register:
    path: /register
    methods: [POST]
    defaults:
        _controller: bcrm.web.controller.event:registerAction

bcrmweb_registration_ok:
    path: /registration/ok
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
        path: Registrierung/Ok

bcrm_registration_confirm:
    path: /registration/confirm/{id}/{key}
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.event:confirmRegistrationAction

bcrmweb_registration_confirmed:
    path: /registrierung/aktiviert
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
        path: Registrierung/Aktiviert
