# Static pages
bcrmweb_index:
    path: /
    methods:  [GET]
    defaults:
        _controller: bcrm.web.controller.web:indexAction

bcrmweb_sessions:
    path: /sessions
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
        path: Sessions

bcrmweb_page:
    path: /p/{path}
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
    requirements:
        path: ".+"

bcrmweb_content:
    path: /c/{path}
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:contentAction
    requirements:
        path: ".+"

bcrmweb_event_register:
    path: /anmeldung
    methods: [GET,POST]
    defaults:
        _controller: bcrm.web.controller.event:registerAction

bcrmweb_registration_ok:
    path: /anmeldung/ok
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
        path: Registrierung/Ok

bcrm_registration_confirm:
    path: /anmeldung/bestaetigen/{id}/{key}
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.event:confirmRegistrationAction

bcrmweb_registration_confirmed:
    path: /anmeldung/aktiviert
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
        path: Registrierung/Aktiviert

bcrmweb_event_unregister:
    path: /stornierung
    methods: [GET,POST]
    defaults:
        _controller: bcrm.web.controller.event:unregisterAction

bcrmweb_unregistration_ok:
    path: /stornierung/ok
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
        path: Stornierung/Ok

bcrm_unregistration_confirm:
    path: /stornierung/bestaetigen/{id}/{key}
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.event:confirmUnregistrationAction
                           
bcrmweb_unregistration_confirmed:
    path: /stornierung/aktiviert
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
        path: Stornierung/Aktiviert

bcrmweb_event_cancel_ticket:
    path: /stornierung/{id}/{code}
    methods: [GET,POST]
    defaults:
        _controller: bcrm.web.controller.event:cancelTicketAction

bcrmweb_event_checkin:
    path: /checkin/{id}/{code}
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.checkin:checkinAction

bcrmweb_concierge_index:
    path: /concierge
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.concierge:indexAction

bcrmweb_concierge_create_ticket:
    path: /concierge/ticket/new
    methods: [GET,POST]
    defaults:
        _controller: bcrm.web.controller.concierge:createTicketAction

bcrmweb_event_manual_checkin:
    path: /concierge/checkin
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.concierge:manualCheckinAction

bcrmweb_concierge_ticketsearch_api:
    path: /api/concierge/ticketsearch
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.concierge:searchTicketAction

bcrmweb_stats:
    path: /stats.{_format}
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.stats:statsAction
        _format: html
    requirements:
        _format: html|json