# Static pages
bcrmweb_index:
    path: /
    methods:  [GET]
    defaults:
        _controller: bcrm.web.controller.web:indexAction

bcrmweb_page:
    path: /p/{path}
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
    requirements:
        path: ".+"

bcrmweb_content:
    path: /c/{path}
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:contentAction
    requirements:
        path: ".+"

bcrmweb_event_register:
    path: /anmeldung
    methods: [GET,POST]
    defaults:
        _controller: bcrm.web.controller.event:registerAction

bcrmweb_registration_ok:
    path: /anmeldung/ok
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
        path: Registrierung/Ok

bcrm_registration_confirm:
    path: /anmeldung/bestaetigen/{id}/{key}
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.event:confirmRegistrationAction

bcrmweb_registration_confirmed:
    path: /anmeldung/aktiviert
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
        path: Registrierung/Aktiviert

bcrmweb_event_unregister:
    path: /stornierung
    methods: [GET,POST]
    defaults:
        _controller: bcrm.web.controller.event:unregisterAction

bcrmweb_unregistration_ok:
    path: /stornierung/ok
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
        path: Stornierung/Ok

bcrm_unregistration_confirm:
    path: /stornierung/bestaetigen/{id}/{key}
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.event:confirmUnregistrationAction
                           
bcrmweb_unregistration_confirmed:
    path: /stornierung/aktiviert
    methods: [GET]
    defaults:
        _controller: bcrm.web.controller.web:pageAction
        path: Stornierung/Aktiviert

bcrmweb_event_cancel_ticket:
    path: /stornierung/{id}/{code}
    methods: [GET,POST]
    defaults:
        _controller: bcrm.web.controller.event:cancelTicketAction
