bcrmprint_printing_queue:
    path: /queue
    methods: [GET]
    defaults:
        _controller: bcrm.print.controller.printing:queueAction

bcrmprint_ticket:
    path: /ticket/{id}/{code}
    methods: [PATCH,DELETE]
    defaults:
        _controller: bcrm.print.controller.printing:printAction