<?php

namespace BCRM\BackendBundle\Entity\Newsletter;

use Doctrine\ORM\EntityRepository;
use PhpOption\None;
use PhpOption\Some;

/**
 * SubscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DoctrineSubscriptionRepository extends EntityRepository implements SubscriptionRepository
{
    /**
     * @param $email
     *
     * @return \PhpOption\Option|void
     */
    public function getSubscription($email)
    {
        $qb = $this->createQueryBuilder('s');
        $qb->andWhere('s.email = :email')->setParameter('email', $email);
        $subscription = $qb->getQuery()->getOneOrNullResult();
        return $subscription === null ? None::create() : new Some($subscription);
    }

}
